name: release

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    outputs:
      before: ${{ steps.version.outputs.version }}
      after: ${{ steps.minecraft.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - id: minecraft
        uses: mcenv/setup-minecraft@main
  release:
    needs: check
    if: ${{ needs.check.outputs.before != needs.check.outputs.after }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: gradle/wrapper-validation-action@v1
      - uses: mcenv/setup-minecraft@main
      - run: |
          java -jar minecraft/server.jar nogui
          java -cp "$(unzip -p minecraft/server.jar META-INF/classpath-joined)" net.minecraft.data.Main --server
      - run: ./gradlew run
      - uses: actions/upload-artifact@v3
        with:
          name: VanillaFree
          path: |
            VanillaFree0.zip
            VanillaFree1.zip
      - run: |
          echo "${{ steps.minecraft.outputs.version }}" > VERSION
          git config --global user.name "intsuc"
          git config --global user.email "intsuc@users.noreply.github.com"
          git commit -am "${{ steps.minecraft.outputs.version }}"
          git push
